version: "3.8"

services:
  user_management_service:
    build:
      context: ./services/user_management
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - user_db
    networks:
      - my_network
    ports:
      - "5000:5000"

  product_management_service:
    build:
      context: ./services/product_management
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - product_db
    networks:
      - my_network
    ports:
      - "5002:5002"

  cart_order_management_service:
    build:
      context: ./services/cart_order_management
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - cart_order_db
    networks:
      - my_network
    ports:
      - "5003:5003"

  sales_payment_service:
    build:
      context: ./services/sales_payment
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - sales_payment_db
    networks:
      - my_network
    ports:
      - "5001:5001"

  return_refund_service:
    build:
      context: ./services/return_refund
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - return_refund_db
    networks:
      - my_network
    ports:
      - "5004:5004"

  # Datenbankdienste
  user_db:
    image: mariadb:latest
    env_file:
      - .env
    networks:
      - my_network
    volumes:
      - user_db_data:/var/lib/mysql
      - ./db_dumps/user_management.sql:/docker-entrypoint-initdb.d/user_management.sql

  product_db:
    image: mariadb:latest
    env_file:
      - .env
    networks:
      - my_network
    volumes:
      - product_db_data:/var/lib/mysql
      - ./db_dumps/product_management.sql:/docker-entrypoint-initdb.d/product_management.sql

  cart_order_db:
    image: mariadb:latest
    env_file:
      - .env
    networks:
      - my_network
    volumes:
      - cart_order_db_data:/var/lib/mysql
      - ./db_dumps/cart_order_management.sql:/docker-entrypoint-initdb.d/cart_order_management.sql

  sales_payment_db:
    image: mariadb:latest
    env_file:
      - .env
    networks:
      - my_network
    volumes:
      - sales_payment_db_data:/var/lib/mysql
      - ./db_dumps/sales_payment.sql:/docker-entrypoint-initdb.d/sales_payment.sql

  return_refund_db:
    image: mariadb:latest
    env_file:
      - .env
    networks:
      - my_network
    volumes:
      - return_refund_db_data:/var/lib/mysql
      - ./db_dumps/return_refund.sql:/docker-entrypoint-initdb.d/return_refund.sql

  adminer:
    image: adminer:latest
    ports:
      - 8080:8080
    networks:
      - my_network
    depends_on:
      - user_db
      - product_db
      - cart_order_db
      - sales_payment_db
      - return_refund_db

  api_gateway:
    build: 
      context: ./gateway
    ports:
      - "8000:8000"
    networks:
      - my_network
    depends_on:
      - user_management_service
      - product_management_service
      - cart_order_management_service
      - sales_payment_service
      - return_refund_service

networks:
  my_network:
    driver: bridge

volumes:
  user_db_data:
  product_db_data:
  cart_order_db_data:
  sales_payment_db_data:
  return_refund_db_data:
