services:
  user_management_service:
    build: 
      context: ./services/user_management
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=mariadb://user:password@user_db/user_management
    depends_on:
      - user_db
    networks:
      - my_network
    ports:
      - "5000:5000" 

  product_management_service:
    build: 
      context: ./services/product_management
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=mariadb://user:password@product_db/product_management
    depends_on:
      - product_db
    networks:
      - my_network
    ports:
      - "5002:5002"

  cart_order_management_service:
    build: 
      context: ./services/cart_order_management
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=mariadb://user:password@cart_order_db/cart_order_management
    depends_on:
      - cart_order_db
    networks:
      - my_network
    ports:
      - "5003:5003"

  sales_payment_service:
    build: 
      context: ./services/sales_payment
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=mariadb://user:password@sales_payment_db/sales_payment
    depends_on:
      - sales_payment_db
    networks:
      - my_network
    ports:
      - "5001:5001"

  return_refund_service:
    build: 
      context: ./services/return_refund
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=mariadb://user:password@return_refund_db/return_refund
    depends_on:
      - return_refund_db
    networks:
      - my_network
    ports:
      - "5004:5004"

networks:
  my_network:
    driver: bridge