version: "3.8"

services:
  user_management_service:
    build:
      context: ./services/user_management
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - DATABASE_URL=mariadb://${USER_DB_USER}:${USER_DB_PASSWORD}@user_db/${USER_DB_NAME}
    depends_on:
      - user_db
    networks:
      - my_network
    ports:
      - "5000:5000"

  product_management_service:
    build:
      context: ./services/product_management
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - DATABASE_URL=mariadb://${PRODUCT_DB_USER}:${PRODUCT_DB_PASSWORD}@product_db/${PRODUCT_DB_NAME}
    depends_on:
      - product_db
    networks:
      - my_network
    ports:
      - "5002:5002"

  cart_order_management_service:
    build:
      context: ./services/cart_order_management
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - DATABASE_URL=mariadb://${CART_ORDER_DB_USER}:${CART_ORDER_DB_PASSWORD}@cart_order_db/${CART_ORDER_DB_NAME}
    depends_on:
      - cart_order_db
    networks:
      - my_network
    ports:
      - "5003:5003"

  sales_payment_service:
    build:
      context: ./services/sales_payment
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - DATABASE_URL=mariadb://${SALES_PAYMENT_DB_USER}:${SALES_PAYMENT_DB_PASSWORD}@sales_payment_db/${SALES_PAYMENT_DB_NAME}
    depends_on:
      - sales_payment_db
    networks:
      - my_network
    ports:
      - "5001:5001"

  return_refund_service:
    build:
      context: ./services/return_refund
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - DATABASE_URL=mariadb://${RETURN_REFUND_DB_USER}:${RETURN_REFUND_DB_PASSWORD}@return_refund_db/${RETURN_REFUND_DB_NAME}
    depends_on:
      - return_refund_db
    networks:
      - my_network
    ports:
      - "5004:5004"

  # Datenbankdienste
  user_db:
    image: mariadb:latest
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${USER_DB_PASSWORD}
      - MYSQL_DATABASE=${USER_DB_NAME}
    networks:
      - my_network
    volumes:
      - user_db_data:/var/lib/mysql

  product_db:
    image: mariadb:latest
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${PRODUCT_DB_PASSWORD}
      - MYSQL_DATABASE=${PRODUCT_DB_NAME}
    networks:
      - my_network
    volumes:
      - product_db_data:/var/lib/mysql

  cart_order_db:
    image: mariadb:latest
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${CART_ORDER_DB_PASSWORD}
      - MYSQL_DATABASE=${CART_ORDER_DB_NAME}
    networks:
      - my_network
    volumes:
      - cart_order_db_data:/var/lib/mysql

  sales_payment_db:
    image: mariadb:latest
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${SALES_PAYMENT_DB_PASSWORD}
      - MYSQL_DATABASE=${SALES_PAYMENT_DB_NAME}
    networks:
      - my_network
    volumes:
      - sales_payment_db_data:/var/lib/mysql

  return_refund_db:
    image: mariadb:latest
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${RETURN_REFUND_DB_PASSWORD}
      - MYSQL_DATABASE=${RETURN_REFUND_DB_NAME}
    networks:
      - my_network
    volumes:
      - return_refund_db_data:/var/lib/mysql

  adminer:
    image: adminer:latest
    container_name: adminer
    ports:
      - 8080:8080
    networks:
      - my_network
    depends_on:
      - user_db
      - product_db
      - cart_order_db
      - sales_payment_db
      - return_refund_db

  api_gateway:
    build: 
      context: ./gateway
    ports:
      - "8000:8000"
    networks:
      - my_network
    depends_on:
      - user_management_service
      - product_management_service
      - cart_order_management_service
      - sales_payment_service
      - return_refund_service

networks:
  my_network:
    driver: bridge

volumes:
  user_db_data:
  product_db_data:
  cart_order_db_data:
  sales_payment_db_data:
  return_refund_db_data:
